"""initial migration

Revision ID: eb3f9547388c
Revises: 
Create Date: 2025-03-04 21:12:36.821423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb3f9547388c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_form_name'), ['name'], unique=True)

    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subject_name'), ['name'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('exam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('term', sa.String(length=50), nullable=True),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_form_id'), ['form_id'], unique=False)

    op.create_table('school_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('class_teacher_id', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_teacher_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_class', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_class_class_teacher_id'), ['class_teacher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_class_form_id'), ['form_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_class_name'), ['name'], unique=True)

    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_user_id'), ['user_id'], unique=False)

    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('school_class_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('admission_number', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['school_class_id'], ['school_class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_admission_number'), ['admission_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_student_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_school_class_id'), ['school_class_id'], unique=False)

    op.create_table('teacher_subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teacher_subject', schema=None) as batch_op:
        batch_op.create_index('idx_teacher_subject_subject_id', ['subject_id'], unique=False)
        batch_op.create_index('idx_teacher_subject_teacher_id', ['teacher_id'], unique=False)

    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_result_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_result_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_result_subject_id'), ['subject_id'], unique=False)

    op.create_table('student_subject',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'subject_id')
    )
    with op.batch_alter_table('student_subject', schema=None) as batch_op:
        batch_op.create_index('idx_student_subject_student_id', ['student_id'], unique=False)
        batch_op.create_index('idx_student_subject_subject_id', ['subject_id'], unique=False)

    op.create_table('welfare_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('welfare_report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_welfare_report_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('welfare_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_welfare_report_student_id'))

    op.drop_table('welfare_report')
    with op.batch_alter_table('student_subject', schema=None) as batch_op:
        batch_op.drop_index('idx_student_subject_subject_id')
        batch_op.drop_index('idx_student_subject_student_id')

    op.drop_table('student_subject')
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_result_subject_id'))
        batch_op.drop_index(batch_op.f('ix_result_student_id'))
        batch_op.drop_index(batch_op.f('ix_result_exam_id'))

    op.drop_table('result')
    with op.batch_alter_table('teacher_subject', schema=None) as batch_op:
        batch_op.drop_index('idx_teacher_subject_teacher_id')
        batch_op.drop_index('idx_teacher_subject_subject_id')

    op.drop_table('teacher_subject')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_school_class_id'))
        batch_op.drop_index(batch_op.f('ix_student_parent_id'))
        batch_op.drop_index(batch_op.f('ix_student_admission_number'))

    op.drop_table('student')
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_user_id'))

    op.drop_table('teacher')
    with op.batch_alter_table('school_class', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_class_name'))
        batch_op.drop_index(batch_op.f('ix_school_class_form_id'))
        batch_op.drop_index(batch_op.f('ix_school_class_class_teacher_id'))

    op.drop_table('school_class')
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_form_id'))

    op.drop_table('exam')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subject_name'))

    op.drop_table('subject')
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_form_name'))

    op.drop_table('form')
    # ### end Alembic commands ###
